### PR TITLE
Resolve failing Xray tests

### PR DESCRIPTION
**Pull request by romelusw**
- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by romelusw** [comment]
@eyalb4doc

**Comment by romelusw** [comment]
@eyalb4doc please review

**Comment by romelusw** [comment]
@eyalbe4 @yoav

**Comment by eyalbe4** [comment]
@romelusw -
I see that @asafgabai is currently discussing this issue with you in https://github.com/jfrog/jfrog-client-go/issues/468.  Hopefully you two can conclude the discussion there soon.

**Comment by romelusw** [comment]
Closing this as @asafgabai change in https://github.com/jfrog/jfrog-client-go/issues/468 addresses this issue.

**Pull request closed without merging**
