### PR TITLE
add context to managers

### LINKED ISSUE #192: Add context.Context management
Hello,

Unless I'm mistaken, your client has no context.Context management. 
Also, would you be able to expose a method to define the context.Context and thus manage the propagation of cancel, timeout, ...?

Thank you in advance.

Regards.

### PR DESCRIPTION
**Pull request by filintod**
- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----
This add a context to the managers so they can execute http requests using a provided context. It probably fixes #192

### CODE REVIEW

**Comment by filintod** [comment]
---

_I have read the CLA Document and I hereby sign the CLA_

---

**Comment by filintod** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
LIKE @filintod!
Let's also update the REAME accordingly.

**Comment by filintod** [comment]
@eyalbe4 readme updated with a minor section, let me know if that's ok or need more info

**Review by eyalbe4 — APPROVED** [review]

**Pull request merged**
