### PR TITLE
feat(get-all-groups): Add Client API to get all groups from Artifactory

### PR DESCRIPTION
**Pull request by ChocPanda**
- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by ChocPanda** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ChocPanda** [comment]
HI @eyalbe4, I see all the tests are passing, what's the process for getting this merged and released?

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
Notice that the existing `GetGroup` API is included in the text is included in the existing `testCreateGroup` - 
image

I suggest adding `testGroupService.GetAllGroups` to the same test function, right after the existing `testGroupService.GetGroup`, so that the new API is tested as well.

**Comment by ChocPanda** [comment]
Hey @eyalbe4, thanks for the suggestion, I've added the additional tests

**Comment by ChocPanda** [comment]
Hey @eyalbe4 any chance of getting a re-review?

**Pull request merged**
