### PR TITLE
New Terraform & PHP Composer repositories support

### PR DESCRIPTION
**Pull request by yesnault**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@yesnault,
It appreads that the new `remoteTerraformTest` added by this PR fails.
image
See the full tests log [here](https://github.com/jfrog/jfrog-client-go/actions/runs/6968493391/job/18962849428?pr=780).

**Comment by yesnault** [comment]
@eyalbe4 it's fixed

**Comment by eyalbe4** [comment]
The Go Tests are still failing @yesnault.
image

**Comment by eyalbe4** [comment]
@yesnault,
There's a chance that test is failing since 12 seconds isn't sufficient time for Artifactory to create the repository.
image
I recommend trying to increase the 12 attempts value to 30
image

**Comment by yesnault** [comment]
>  I recommend trying to increase the 12 attempts value to 30 

ok, updated

**Pull request merged**
