### PR TITLE
Add external dependencies rewrite parameters for helm remote repos

### PR DESCRIPTION
**Pull request by fabianrindlisbacher**
- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by fabianrindlisbacher** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fabianrindlisbacher** [comment]
The changes are needed to implement the new dependency rewrite functionality describe here: https://www.jfrog.com/confluence/display/JFROG/Kubernetes+Helm+Chart+Repositories -> Under Remote Repositories

**Comment by fabianrindlisbacher** [comment]
@eyalbe4 @sverdlov93 can you review these changes?

**Review by yahavi — APPROVED** [review]
Thanks for this contribution, @fabianrindlisbacher!

**Pull request merged**
