### PR TITLE
go fmt ./...

### PR DESCRIPTION
**Pull request by sebinjohn**

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thanks for this PR @sebinjohn!
Can you please create the this PR on the *dev* branch? See the **Guidelines** section on the README.

**Comment by sebinjohn** [comment]
@eyalbe4 Ah forgot about that. Done. Closing this PR.

How about making the `dev` branch the base branch of the repo?

**Comment by eyalbe4** [comment]
Thanks @sebinjohn.
Well, we wanted to make sure that people who are building the CLI from sources, use the code of the latest release (the code in *master* branch). Code which hasn't been released yet therefore goes into the *dev* branch. Just before the release, the *dev* branch is merged into the *master*.
Let me know what you think.

**Comment by sebinjohn** [comment]
@eyalbe4 Make sense. 👍

**Pull request closed without merging**
