### PR TITLE
feat: Add swift support for local remote virtual and federated repos

### PR DESCRIPTION
**Pull request by nicolazurbruegg**
- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by nicolazurbruegg** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yahavi** [comment]
@nicolazurbruegg thanks for this contribution! We really appreciate it!

Before we merge this PR, could you please add "Swift" to the readme? I can see 4 locations:
1. https://github.com/jfrog/jfrog-client-go#creating-and-updating-local-repository
2. https://github.com/jfrog/jfrog-client-go#creating-and-updating-remote-repository
3. https://github.com/jfrog/jfrog-client-go#creating-and-updating-virtual-repository
4. https://github.com/jfrog/jfrog-client-go#creating-and-updating-federated-repository

**Review by yahavi — APPROVED** [review]
LGTM

**Comment by nicolazurbruegg** [comment]
Do you possibly know how long it takes until the changes are released?

**Pull request merged**
