### PR TITLE
return nil err when a permission target doesn't exist

### PR DESCRIPTION
**Pull request by M0roSan**
- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

Addresses https://github.com/jfrog/jfrog-client-go/issues/336

### CODE REVIEW

**Comment by M0roSan** [comment]
I acknowledge the above comments. Please standby until I get further clarification on my end. Thanks

**Comment by M0roSan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by M0roSan** [comment]
sorry for direct ping @eyalbe4 as i saw you merged the last time. can I get a review?

**Comment by yahavi** [comment]
recheckcla

**Review by yahavi — APPROVED** [review]
LGTM.
@eyalbe4?

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
Thanks for this PR!
This fix is indeed required.
Before we merge this, would mind adding the following?
1. A note in the README, under the *Fetching a Permission Target* saying that if the requested permission target does not exists, a nil value is returned for the *permissionTargetParams* param, with a nil error value?
2. An addition test in *artifactorypermissiontarget_test.go*, checking that if if a non existing permission target is requested, nil is returned for both returned values.

**Comment by M0roSan** [comment]
@eyalbe4 I have added doc and test. also doc for get user and get group

**Pull request merged**
