### PR TITLE
remove omitempty since default is true

### PR DESCRIPTION
**Pull request by matteosilv**
- [X] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [X] This pull request is on the dev branch.
- [X] I used gofmt for formatting the code before submitting the pull request.
-----

FailFast needs to be always printed in the response since it defaults to true

### CODE REVIEW

**Review by yahavi — CHANGES_REQUESTED** [review]
Thanks for your contribution, @matteosilv!
Could you please add a comment above `FailFast` explaining why we don't have `omitempty` in FailFast? It isn't trivial at all.

**Comment by matteosilv** [comment]
Hi @yahavi, without omitempty the value will be always marshalled whether it is true or false. I have a pull request jfrog/jfrog-cli#1070, and basing on existing code of both projects I saw that other fields with true default value are handled this way. In other terms it seems to me that is in charge of jfrog-cli (in these particular case) of handling default values.

**Comment by yahavi** [comment]
@matteosilv 
Yes, It took me some minutes to understand why this change is needed. Therefore I think a comment in the code above `FailFast` is mandatory.

**Review by yahavi — APPROVED** [review]
Thanks @matteosilv!

**Pull request merged**
