### PR TITLE
Correcting Cvess score data types

### PR DESCRIPTION
**Pull request by romelusw**
- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by romelusw** [comment]
@eyalbe4

**Comment by eyalbe4** [comment]
Just an FYI @romelusw -  https://github.com/jfrog/jfrog-client-go/pull/473
I believe that with the new PR we're all good.

**Comment by eyalbe4** [comment]
@romelusw - 
We now see that following your change from string to float64, the following "TestXrayReport/reportAll" test fails.
Since we may need to release jfrog-client-go today, we may have revert the commit of this PR.
Please let us know what you think. 
```
=== RUN   TestXrayReport/reportAll
[Debug] Sending HTTP POST request to: http://localhost:49725//api/v1/reports/vulnerabilities
[Debug] HTTP redirecting to  http://localhost:49725/api/v1/reports/vulnerabilities
[Debug] Sending HTTP POST request to: http://localhost:49725/api/v1/reports/vulnerabilities
[Debug] Sending HTTP GET request to: http://localhost:49725//api/v1/reports/777
[Debug] Sending HTTP POST request to: http://localhost:49725//api/v1/reports/vulnerabilities/777?direction=asc&page_num=0&num_of_rows=7&order_by=severity
[Debug] HTTP redirecting to  http://localhost:49725/api/v1/reports/vulnerabilities/777?direction=asc&page_num=0&num_of_rows=7&order_by=severity
[Debug] Sending HTTP POST request to: http://localhost:49725/api/v1/reports/vulnerabilities/777?direction=asc&page_num=0&num_of_rows=7&order_by=severity
    xrayreport_test.go:67: 
        	Error Trace:	xrayreport_test.go:67
        	Error:      	Received unexpected error:
        	            	json: cannot unmarshal string into Go struct field ReportCve.rows.cves.cvss_v2_score of type float64
        	Test:       	TestXrayReport/reportAll
    xrayreport_test.go:92: 
        	Error Trace:	xrayreport_test.go:92
        	            				xrayreport_test.go:68
        	Error:      	Not equal: 
        	            	expected: 3131
        	            	actual  : 3043
        	Test:       	TestXrayReport/reportAll
[Debug] Sending HTTP DELETE request to: http://localhost:49725//api/v1/reports/777
--- FAIL: TestXrayReport (0.01s)
    --- FAIL: TestXrayReport/reportAll (0.01s)
```

**Comment by RobiNino** [comment]
Hi @romelusw ,
We reverted this commit for the time being to avoid stalling the release planned for today.
We'll be happy to merge this again after the issue with the tests will be resolved.
Thanks

**Comment by romelusw** [comment]
@eyalbe4 the failure had to do with the test data also being as strings rather than floats. I have corrected that here: https://github.com/jfrog/jfrog-client-go/pull/476

**Pull request merged**
