### PR TITLE
Add username and description to access token commands

### PR DESCRIPTION
**Pull request by Mavrickk3**
This PR contains the same changes as https://github.com/jfrog/jfrog-client-go/pull/759, just with updated readme to address the latest change requests: https://github.com/jfrog/jfrog-client-go/pull/759#pullrequestreview-1538673278

- [x] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jfrog-client-go/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by Mavrickk3** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Mavrickk3** [comment]
recheck

**Comment by Mavrickk3** [comment]
recheck

**Comment by eyalbe4** [comment]
recheck

**Comment by eyalbe4** [comment]
recheck

**Comment by yahavi** [comment]
@Mavrickk3 
Thanks for your contribution!

Your code appears to be committed under the user @ngergely6, but you initiated this Pull Request using your own user. This situation is causing the CLA assistant to prevent us from proceeding with this PR.

To resolve this, please update your local Git user configuration and replace the commit with the @Mavrickk3 user. This should help us move forward with the PR smoothly.

**Comment by eyalbe4** [comment]
@Mavrickk3,
With your permission, I'm closing this PR, since it seems to be a duplicate of https://github.com/jfrog/jfrog-client-go/pull/759. Feel free to reopen it if needed.

**Pull request closed without merging**
