### PR TITLE
make sure statuses are included with the buildinfo.

### LINKED ISSUE #356: BuildInfo struct is missing `statuses` key
**Describe the bug**
The [BuildInfo struct](https://github.com/jfrog/jfrog-client-go/blob/3c8c27e0b2fd6411d9c646e50e35e275b42528f0/artifactory/buildinfo/buildinfo.go#L106-L119) is missing the `statuses` key, which contains build promotion/release information. 

**To Reproduce**
Look here: https://github.com/jfrog/jfrog-client-go/blob/3c8c27e0b2fd6411d9c646e50e35e275b42528f0/artifactory/buildinfo/buildinfo.go#L106-L119

**Expected behavior**
The BuildInfo struct should be modified to look like the following:

```golang
type BuildInfo struct {
    Name                     string   `json:"name,omitempty"`
    Number                   string   `json:"number,omitempty"`
    Agent                    *Agent   `json:"agent,omitempty"`
    BuildAgent               *Agent   `json:"buildAgent,omitempty"`
    Modules                  []Module `json:"modules,omitempty"`
    Started                  string   `json:"started,omitempty"`
    Properties               Env      `json:"properties,omitempty"`
    ArtifactoryPrincipal     string   `json:"artifactoryPrincipal,omitempty"`
    BuildUrl                 string   `json:"url,omitempty"`
    Issues                   *Issues  `json:"issues,omitempty"`
    ArtifactoryPluginVersion string   `json:"artifactoryPluginVersion,omitempty"`
    VcsList                  []Vcs    `json:"vcs,omitempty"`
    Statuses                 []Status `json:"statuses,omitempty"`
}

type Status struct {
    Status       string    `json:"status,omitempty"`
    Comment string `json:"comment,omitempty"`
    Timestamp time.Time `json:"timestamp,omitempty"`
    User string `json:"user,omitempty"`
    CiUser string `json:"ciUser,omitempty"`
    TimestampDate int64 `json:"timestampDate,omitempty"`
}

```

**Versions**
- JFrog Go client version: 
- JFrog Go client operating system:
- Artifactory version:

**Additional context**

### PR DESCRIPTION
**Pull request by AnalogJ**
- [ ] All [tests](https://github.com/jfrog/jfrog-client-go#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used gofmt for formatting the code before submitting the pull request.
-----

fixes #356

### CODE REVIEW

**Review by yahavi — CHANGES_REQUESTED** [review]
@AnalogJ 
Thanks for this contribution!
Please see my inline comment.

**Comment by eyalbe4** [comment]
@AnalogJ,
Since we're currently considering to make major changes and improvements to the entire build promotion process, I suggest that for now, we wait with changes to the build-info schema to include promotion statuses.

**Comment by AnalogJ** [comment]
Hi @eyalbe4 
I'd really like to get this merged if possible. 
Any chance you could provide an update about the future of Promotion status's in this library? 

I've also rebased my branch on the latest from master.

**Comment by AnalogJ** [comment]
Hey @eyalbe4 @yahavi 
Any additional feedback for this PR?

**Comment by AnalogJ** [comment]
@eyalbe4 @yahavi any updates here? Sorry to keep bugging you

**Comment by eyalbe4** [comment]
@AnalogJ,
Since this change may conflict with other planned changes to the build promotion process, will you be able to share more details about the need? How are you planning to use and consume this data?
With this information, maybe we'll be able to come up with an alternative solution.

**Comment by AnalogJ** [comment]
Hey,
This is a critical feature for us. Basically we use the Jfrog Go SDK to create "Builds".
The builds contain a list of versioned artifacts that will be used in a deployment. These artifacts are then scanned using XRAY, and deployed to various non-production environments automatically. The "PromotionStatus" field is used as a manual flag to ensure that Production Deployments can only use vetted/production-ready artifacts.

**Comment by eyalbe4** [comment]
I see @AnalogJ.
Would you be willing perhaps to tag the build-info artifact in Artifactory, with a property that will indicate the status of the build? Every time you publish a build-info, it is also saved as a file under the *artifactory-build-info* repository. You can set and get the value of this custom property on/from the build-info artifact, to support your logic.
This functionality is supported by this library as well. See the [Setting Properties on Files in Artifactory](https://github.com/jfrog/jfrog-client-go#setting-properties-on-files-in-artifactory) and [Deleting Properties from Files in Artifactory](https://github.com/jfrog/jfrog-client-go#deleting-properties-from-files-in-artifactory) sections in the README.

**Comment by AnalogJ** [comment]
This PR doesnt seem relevant since https://github.com/jfrog/jfrog-client-go/blob/master/artifactory/services/promote.go is merged. Closing.

**Pull request closed without merging**
